-- Banco de dados do Novo Rumo
CREATE TABLE IF NOT EXISTS senhas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  senha VARCHAR(64) NOT NULL UNIQUE,
  status ENUM('ativa','usada','bloqueada') NOT NULL DEFAULT 'ativa',
  device_fingerprint VARCHAR(128) DEFAULT NULL,
  ativada_em DATETIME DEFAULT NULL,
  criada_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS progresso (
  id INT AUTO_INCREMENT PRIMARY KEY,
  senha_id INT NOT NULL,
  etapa INT NOT NULL DEFAULT 1,
  modulo INT NOT NULL DEFAULT 0,
  concluido BOOLEAN NOT NULL DEFAULT FALSE,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (senha_id) REFERENCES senhas(id) ON DELETE CASCADE,
  UNIQUE KEY (senha_id)
);

CREATE TABLE IF NOT EXISTS respostas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  senha_id INT NOT NULL,
  modulo_id VARCHAR(64) NOT NULL,
  valor TEXT,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (senha_id) REFERENCES senhas(id) ON DELETE CASCADE,
  UNIQUE KEY (senha_id, modulo_id)
);

CREATE TABLE IF NOT EXISTS admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(64) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL
);
